//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WhatsYummy.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Avaliacao
    {
        public int ID { get; set; }
        public double Classificaçao { get; set; }
        public string Comentario { get; set; }
        public int UtilizadorId { get; set; }
        public int ProdutoId { get; set; }
        public int EstabelecimentoId { get; set; }
        public string Foto { get; set; }
    
        public virtual Produto Produto { get; set; }
        public virtual Utilizador Utilizador { get; set; }
    }
}
