//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using Newtonsoft.Json;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net;
using System.Web;


namespace WhatsYummy.Models
{
    using System;
    using System.Collections.Generic;
    using System.IO;

    public partial class Estabelecimento
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Estabelecimento()
        {
            this.Horario = new HashSet<Horario>();
            this.Produto = new HashSet<Produto>();
        }
    
        public int ID { get; set; }
        public string Nome { get; set; }
        public string CodigoPostal { get; set; }
        public string Localidade { get; set; }
        public string Rua { get; set; }
        public Nullable<int> UtilizadorId { get; set; }
        public int Estado { get; set; }
    
        public virtual Utilizador Utilizador { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Horario> Horario { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Produto> Produto { get; set; }


        public int getDistance(string location) {
            //string key = "AIzaSyD9Fz8X1RTyq6jXHuFUaAV2EvWh0oynCS4";
            string key = "AIzaSyBqO8i-_iKuV6lob3DTP8TCmXXzoR00g5g";
           
            string json;
            string sURL = "https://maps.googleapis.com/maps/api/distancematrix/json?origins=" + location + "&destinations=" +Rua+", "+CodigoPostal+" "+Localidade+"&key=" + key;
            using (WebClient client = new WebClient())
                try
                {
                    json = client.DownloadString(sURL);
                }
                catch (Exception e)
                {
                    return 26000;
                }

            dynamic obj = JsonConvert.DeserializeObject(json);

           if (obj == null || obj.rows[0].elements[0].distance == null)
                return -1;

           return obj.rows[0].elements[0].distance.value;
        }
    }
 }
