//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WhatsYummy.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Visita
    {
        public int ID { get; set; }
        public int UtlizadorId { get; set; }
        public int ProdutoId { get; set; }
        public int EstabelecimentoId { get; set; }
        public System.DateTime Data { get; set; }
    
        public virtual UtilizadorProduto UtilizadorProduto { get; set; }
    }
}
